### PR TITLE
Fix PriceText. Add Nyc coverage

### LINKED ISSUE #230: "Free" price not properly labeled
https://travis-ci.org/facundoolano/google-play-scraper/builds/372416218

``` 
 1) App method should fetch valid application data:
     AssertionError: expected '' to equal 'Free'
      at gplay.app.then (test/lib.app.js:43:16)
      at process._tickCallback (internal/process/next_tick.js:178:7)
  2) List method should fetch apps with fullDetail:
     AssertionError: expected '' to equal 'Free'
      at apps.map (test/lib.list.js:93:14)
      at Array.map (<anonymous>)
      at gplay.list.then.then (test/lib.list.js:75:26)
      at process._tickCallback (internal/process/next_tick.js:178:7)
```

### PR DESCRIPTION
**Pull request by srikanthlogic**
* Fixes #230 
* Added nyc for coverage reporting.

### CODE REVIEW

File: lib/app.js [hunk 1]
```diff
@@ -176,6 +179,14 @@ function descriptionText (description) {
   return cheerio.text(html('div'));
 }
 
+function priceTextForFree (priceText) {
```
Comment (facundoolano) [inline lib/app.js]: `priceText` would be a better name for this function.
